#!/bin/bash
# PreToolUse hook: Block edits to shadcn-vue auto-generated UI components
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if echo "$FILE_PATH" | grep -q '/components/ui/'; then
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Files in src/components/ui/ are auto-generated by shadcn-vue and must not be edited manually. To add new UI components, run: npx shadcn-vue@latest add <component-name>"}}'
  exit 0
fi

exit 0
